# Generated by Django 5.2 on 2025-05-03 16:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('fruit', 'Fruit'), ('veg', 'Vegetable'), ('protein', 'Protein'), ('grain', 'Grain'), ('other', 'Other')], max_length=20)),
                ('date_logged', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
