# Generated by Django 5.2 on 2025-05-03 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_groceryitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='groceryitem',
            name='quantity',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
