# Generated by Django 5.2 on 2025-05-03 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_alter_foodlog_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodlog',
            name='category',
            field=models.CharField(choices=[('fruit', 'Fruit'), ('vegetable', 'Vegetable'), ('protein', 'Protein'), ('grain', 'Grain'), ('dairy', 'Dairy'), ('fish', 'Fish'), ('frozen', 'Frozen'), ('dessert', 'Dessert'), ('wine', 'Wine'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
