# Generated by Django 5.2 on 2025-05-06 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_groceryitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodlog',
            name='calcium',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='foodlog',
            name='calories',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='foodlog',
            name='carbs',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='foodlog',
            name='cholesterol',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='foodlog',
            name='fat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='foodlog',
            name='fiber',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='foodlog',
            name='iron',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='foodlog',
            name='magnesium',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='foodlog',
            name='potassium',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='foodlog',
            name='protein',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='foodlog',
            name='saturated_fat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='foodlog',
            name='sodium',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='foodlog',
            name='sugars',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='foodlog',
            name='vitamin_a',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='foodlog',
            name='vitamin_b12',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='foodlog',
            name='vitamin_c',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='foodlog',
            name='vitamin_d',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='foodlog',
            name='zinc',
            field=models.FloatField(default=0.0),
        ),
    ]
