# Generated by Django 5.2 on 2025-05-06 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_alter_foodlog_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodlog',
            name='quantity',
        ),
        migrations.AddField(
            model_name='foodlog',
            name='quantity_amount',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='foodlog',
            name='quantity_unit',
            field=models.CharField(choices=[('cup', 'Cup(s)'), ('oz', 'Ounce(s)'), ('g', 'Gram(s)'), ('tbsp', 'Tablespoon(s)'), ('tsp', 'Teaspoon(s)'), ('ml', 'Milliliter(s)'), ('l', 'Liter(s)'), ('slice', 'Slice(s)'), ('piece', 'Piece(s)')], default='oz', max_length=20),
        ),
    ]
