# Generated by Django 5.2 on 2025-05-07 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_remove_foodlog_quantity_foodlog_quantity_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodlog',
            name='quantity_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PantryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.FloatField(default=1)),
                ('unit', models.CharField(choices=[('g', 'grams'), ('oz', 'ounces'), ('ml', 'milliliters'), ('cups', 'cups'), ('pieces', 'pieces'), ('cans', 'cans'), ('bags', 'bags'), ('boxes', 'boxes'), ('tbsp', 'tbsp'), ('tsp', 'tsp')], max_length=20)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
