# Generated by Django 5.2 on 2025-05-07 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_alter_foodlog_quantity_amount_pantryitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pantryitem',
            name='unit',
            field=models.CharField(choices=[('none', '—'), ('g', 'grams'), ('oz', 'ounces'), ('ml', 'milliliters'), ('cups', 'cups'), ('pieces', 'pieces'), ('cans', 'cans'), ('bags', 'bags'), ('boxes', 'boxes'), ('tbsp', 'tbsp'), ('tsp', 'tsp')], max_length=20),
        ),
    ]
