# Generated by Django 5.2 on 2025-05-07 19:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_alter_pantryitem_unit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pantryitem',
            name='unit',
            field=models.CharField(blank=True, choices=[('g', 'grams'), ('oz', 'ounces'), ('ml', 'milliliters'), ('cups', 'cups'), ('pieces', 'pieces'), ('cans', 'cans'), ('bags', 'bags'), ('boxes', 'boxes'), ('tbsp', 'tbsp'), ('tsp', 'tsp')], max_length=20),
        ),
        migrations.CreateModel(
            name='SupplementLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('time_of_day', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening')], max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
