# Generated by Django 5.2 on 2025-05-09 01:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_alter_pantryitem_unit_supplementlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodlog',
            name='calories',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='foodlog',
            name='quantity_unit',
            field=models.CharField(blank=True, choices=[('piece', 'Piece(s)'), ('slice', 'Slice(s)'), ('fruit', 'Fruit'), ('g', 'Grams'), ('oz', 'Ounces'), ('cup', 'Cups'), ('serving', 'Serving')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pantryitem',
            name='unit',
            field=models.CharField(blank=True, choices=[('piece', 'Piece(s)'), ('slice', 'Slice(s)'), ('fruit', 'Fruit'), ('g', 'Grams'), ('oz', 'Ounces'), ('cup', 'Cups'), ('serving', 'Serving')], max_length=20),
        ),
        migrations.CreateModel(
            name='SavedRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spoonacular_id', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('image_url', models.URLField()),
                ('source_url', models.URLField()),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'spoonacular_id')},
            },
        ),
    ]
